//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int inventoryId { get; set; }
        public string inventoryName { get; set; }
        public Nullable<int> inventoryQuantity { get; set; }
    }
}
